controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz
        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController



position_controller:
    ros__parameters:
        joints:
        - joint1_arm_joint
        - joint2_arm_joint
        - joint3_arm_joint
        - joint4_arm_joint
        - joint5_arm_joint
        - joint6_link_joint
        interface_name: position
        command_interfaces:
        - position
        state_interfaces:
        - position
        - velocity


velocity_controller:
    ros__parameters:
        joints:
        - left_front_wheel_joint
        - right_front_wheel_joint
        - left_rear_wheel_joint
        - right_rear_wheel_joint
        interface_name: velocity
        command_interfaces:
        - velocity
        state_interfaces:
        - position
        - velocity